apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-2
  namespace: app
spec:
  # The interval at which to reconcile the Helm release
  interval: 2m
  chart:
    spec:
      # The name of the chart as made available by the HelmRepository
      # (without any aliases)
      chart: podinfo
      # A fixed SemVer, or any SemVer range
      # (i.e. >=4.0.0 <5.0.0)
      version: 3.2.0
      # The reference to the HelmRepository
      sourceRef:
        kind: HelmRepository
        name: podinfo-h3
        # Optional, defaults to the namespace of the HelmRelease
        namespace: default